# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  my_python_job:
    name: "Python"
    runs-on: ubuntu-latest

    steps:
    - name: Setup python  
    - uses: actions/checkout@v2
      with: 
        python-version: "3.8"


    - name: install pyenv
      id: pyenv_installation
      uses: gabrielfalcao/pyenv-action@v5
      with: 
        versions: "3.8"
        commands: |
          pip install -r requirements.txt

  test_pyenv:
    runs-on: ubuntu-latest
    name: install pyenv
    steps:
    - name: setup pyenv
      id: pyenv_installation
      uses: "gabrielfalcao/pyenv-action@v5"


    - name: debug pyenv
      run: echo ${{ steps.pyenv_installation.outputs.pyenv_root }}
       




  
