# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  my_python_job:
    name: "Python"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - 3.6.8
          - 3.7.5

    steps:
    - uses: actions/checkout@v2
    - name: Install python version
      uses: gabrielfalcao/pyenv-action@v5
      with:
        default: "${{ matrix.python }}"
        command: pip install -U pip  # upgrade pip after installing python

    - name: Install dependencies
      run: pip install -r requirements.txt

  test_pyenv:
    runs-on: ubuntu-latest
    name: install pyenv
    steps:
    - name: setup pyenv
      id: pyenv_installation
      uses: "gabrielfalcao/pyenv-action@v5"
      with:
        versions: 3.7.2, 3.8.6
        command: |
          pip install pandas

    - name: debug pyenv
      run: echo ${{ steps.pyenv_installation.outputs.pyenv_root }}
  