name: Using
on: [push, pull_request]

jobs:
  my_python_job:
    name: "Python"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - 3.8.6

    steps:
    - uses: actions/checkout@v2
    - name: Install python version
      uses: gabrielfalcao/pyenv-action@v7
      with:
        default: "${{ matrix.python }}"
        command: pip install -U pip  # upgrade pip after installing python
    
    - name: create environment
      run: pyenv local 3.8.6 && python -mvenv .venv357

    - name: Install dependencies
      run: pip install -r requirements.txt --upgrade pip

