# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test_pyenv:
    runs-on: ubuntu-latest
    name: install pyenv
    steps:
    - name: setup pyenv
      uses: "gabrielfalcao/pyenv-action@v5"
      with:
        versions: 3.7.2, 3.8.6
        command: |
          pip install pandas

    # create virtualenv for each python version

    - name: Create virtualenv for python 3.7.2
      run: pyenv local 3.7.2 && python3 -mvenv .venv372
      
    - name: Create virtualenv for python 3.8.6
      run: pyenv local 3.7.2 && python3 -mvenv .venv386
