name: Continuous Integration
on: [push, pull_request]

jobs:
  jest:
    name: functional tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2


  integration_test_setup:
    runs-on: ubuntu-latest
    name: install pyenv
    steps:
    - name: setup pyenv
      id: pyenv
      uses: "gabrielfalcao/pyenv-action@v7"

    - name: List python versions
      run: pyenv versions

    - name: Verify default installation
      run: python --version

    - name: list files in pyenv_root
      run: ls -lhtr ${{ steps.pyenv.outputs.pyenv_root }}

