name: Using python 3.7.5 with pyenv
on: [push, pull_request]

jobs:

  test_pyenv:
    runs-on: ubuntu-latest
    name: install pyenv
    steps:
    - name: setup pyenv
      uses: "gabrielfalcao/pyenv-action@v7"
      with:
        default: 3.8.6
        command: |
          pip install -U pip setuptools
          pip install -r requirements.txt --upgrade pip

    # create virtualenv for each python version


    - name: Create virtualenv for python 3.8.6
      run: pyenv local 3.7.2 && python3 -mvenv .venv372