name: Using python 3.7.5 with pyenv
on: [push, pull_request]

jobs:

  test_pyenv:
    runs-on: ubuntu-latest
    name: install pyenv
    steps:
    - name: setup pyenv
      uses: "gabrielfalcao/pyenv-action@v5"
      with:
        default: 3.7.2
        versions: 3.6.8, 3.5.7
        command: |
          pip install -U pip setuptools
          pip install -r development.txt --upgrade pip

    # create virtualenv for each python version

    - name: Create virtualenv for python 3.5.7
      run: pyenv local 3.5.7 && python3 -mvenv .venv357

    - name: Create virtualenv for python 3.6.8
      run: pyenv local 3.6.8 && python3 -mvenv .venv365

    - name: Create virtualenv for python 3.7.2
      run: pyenv local 3.7.2 && python3 -mvenv .venv372